AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TopologyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handler
      Runtime: nodejs20.x
      Timeout: 30

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeVpcs
                - ec2:DescribeSubnets
                - ec2:DescribeInstances
                - ec2:DescribeSecurityGroups
                - dynamodb:PutItem
              Resource: "*"

      Events:
        TopologyApi:
          Type: Api
          Properties:
            Path: /topology
            Method: get
