AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NexusOps X Audit Ledger Lambda

Resources:
  AuditLedgerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nexusops-audit-ledger
      Runtime: nodejs20.x
      Handler: src/handler.handler
      CodeUri: .
      Role: arn:aws:iam::093796421952:role/nexus-lambda-role
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          AUDIT_TABLE_NAME: NexusAuditLedger