name: NexusOps Lambda Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        service:
          - auth-nexus
          - threat-sentinel
          - infra-healer
          - event-intelligence
          - data-nexus
          - career-intelligence
          - engineering-intelligence

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build SAM Application
        working-directory: Services/${{ matrix.service }}
        run: sam build

      - name: Deploy SAM Application
        working-directory: Services/${{ matrix.service }}
        run: |
          sam deploy --stack-name nexusops-${{ matrix.service }} --capabilities CAPABILITY_IAM --region eu-north-1 --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
